spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/sfg_prod
    username: sfg_prod_user
#   Should pass password as an environment variable
#   Or, set up encryption on that
    password: guru
    platform: mysql
  jpa:
    hibernate:
#     Let hibernate go in and check the schema, make sure that the schema that
#         it finds is as expected
#     Do not let hibernate do DDL changes
#     validate: validate the schema, makes no changes to the database
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false