# logging.level.guru.springframework=debug
logging:
  level:
    guru.springframework: debug
    # org.springframework: debug
spring:
  data:
    mongodb:
      # Set up a random port
      port: 0
      host: localhost
  # Pretty-print JSON responses
  jackson:
    serialization.INDENT_OUTPUT: true
